const SUPABASEURL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
const SUPABASEKEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? '';

const APIBASEURL = process.env.NEXT_PUBLIC_API_URL ?? '';

if (!SUPABASEURL || !SUPABASEKEY) {
	console.error('SUPABASE URL / KEY KOSONG ATAU UNDEFINED!');
}

if (!APIBASEURL) console.error('API BASE URL KOSONG ATAU UNDEFINED!');

export { SUPABASEURL, SUPABASEKEY, APIBASEURL };
