import { urbanist } from '@/config/fonts';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import { Header } from '@/app/(home)/_components/header';
import './globals.css';
import { TooltipProvider } from '@/components/ui/tooltip';

const figtree = Figtree({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={cn('h-full', 'antialiased', 'font-sans', figtree.variable, urbanist.variable)}>
			<body className="min-h-full flex flex-col">
				<Header />
				<TooltipProvider>{children}</TooltipProvider>
			</body>
		</html>
	);
}
