import { MemberRole } from '@/types/member-role';

export interface TeamMember {
	id: string | number;
    slug: string; 
    name: string;
    role: MemberRole;
    major?: string;
    university?: string;
    originAddress?: string;
    imageUrl?: string;
    description: string;
    instagramUrl?: string;
}

export const TEAM_MEMBERS: TeamMember[] = [
    {
        id: 'tm-00',
        slug: 'nana-sutarna',
        name: 'Nana Sutarna',
        role: MemberRole.DPL,
        major: 'Pendidikan Guru Sekolah Dasar',
        university: 'Universitas Muhammadiyah Kuningan',
        originAddress: 'Perumahan Alam Asri Kasturi Jl Lamtoro D56',
        imageUrl: '/assets/images/team/nana-sutarna.jpeg',
        description: 'Dosen Pembimbing Lapangan KKN Kolaboratif Desa Kuta Kembaran 2026.',
    },
    {
        id: 'tm-01',
        slug: 'ahmad-fauzi',
        name: 'Ahmad Fauzi',
        role: MemberRole.KORDES,
        major: 'Komunikasi Penyiaran Islam',
        university: 'UNISA Kuningan',
        originAddress: 'Desa Karangkamulyan, Kec. Ciawigebang',
        imageUrl: '/assets/images/team/ahmad-fauzi.jpeg',
        description: 'Koordinator Desa yang memimpin dan menyelaraskan seluruh program kerja KKN.',
    },
    {
        id: 'tm-02',
        slug: 'sri-nurdiyanti',
        name: 'Sri Nurdiyanti',
        role: MemberRole.WAKORDES,
        major: 'PAI',
        university: 'UNISA Kuningan',
        originAddress: 'Desa Jalaksana, Kec. Jalaksana, Kab. Kuningan',
        imageUrl: '/assets/images/team/sri-nurdiyanti.jpg',
        description: 'Wakil Koordinator Desa yang bertanggung jawab atas manajemen teknis internal tim.',
    },
    {
        id: 'tm-03',
        slug: 'ari-lesmana',
        name: 'Ari Lesmana',
        role: MemberRole.SEKRETARIS_1,
        major: 'Bisnis Digital',
        university: 'Universitas Kuningan',
        originAddress: 'Desa Cikondang, Kec. Hantara',
        imageUrl: '/assets/images/team/ari-lesmana.png',
        description: 'Sekretaris utama yang mengelola administrasi, surat-menyurat, dan arsip dokumen KKN.',
    },
    {
        id: 'tm-04',
        slug: 'putri-fatimah-azzahra',
        name: 'Putri Fatimah Az-Zahra',
        role: MemberRole.SEKRETARIS_2,
        major: 'PAI',
        university: 'UNISA Kuningan',
        originAddress: 'Desa Kertawirama, Kec. Nusaherang',
        imageUrl: '/assets/images/team/putri-fatimah-azzahra.jpg',
        description: 'Wakil sekretaris yang mendampingi penyusunan laporan proposal dan program kerja.',
    },
    {
        id: 'tm-05',
        slug: 'audia-salsa-nuraenny',
        name: 'Audia Salsa Nuraenny',
        role: MemberRole.BENDAHARA_1,
        major: 'Kesehatan Masyarakat',
        university: 'UBHI',
        originAddress: 'Cigugur, Kuningan',
        imageUrl: '/assets/images/team/audia-salsa-nuraenny.png',
        description: 'Bendahara utama yang bertanggung jawab penuh atas manajemen arus kas pembukuan KKN.',
    },
    {
        id: 'tm-06',
        slug: 'hanum-agnia',
        name: 'Hanum Agnia',
        role: MemberRole.BENDAHARA_2,
        major: 'Ekonomi Syariah',
        university: 'STAIKU',
        originAddress: 'Ds. Kalimukti, Kec. Pabedilan, Kab. Cirebon',
        imageUrl: '/assets/images/team/hanum-agnia.jpg',
        description: 'Wakil bendahara yang mengelola realisasi anggaran tiap divisi lapangan.',
    },
    {
        id: 'tm-07',
        slug: 'hamid-jalalan-qodiri',
        name: 'Hamid Jalalan Qodiri',
        role: MemberRole.ACARA_1,
        major: 'PAI',
        university: 'UNISA Kuningan',
        originAddress: 'Pasapen 3, Kuningan',
        imageUrl: '/assets/images/team/hamid-jalalan-qodiri.jpeg',
        description: 'Penanggung jawab perancang konsep kegiatan dan *timeline* program kerja KKN.',
    },
    {
        id: 'tm-08',
        slug: 'syifaurohmah',
        name: 'Syifaurohmah (Syifa)',
        role: MemberRole.ACARA_2,
        major: 'Manajemen Informasi Kesehatan',
        university: 'Poltekkes KMC Kuningan',
        originAddress: 'Ds. Sukaraja, Kec. Ciawigebang',
        imageUrl: '/assets/images/team/syifaurohmah.jpg',
        description: 'Pelaksana operasional acara yang bertugas mengawal jalannya agenda pengabdian di desa.',
    },
    {
        id: 'tm-09',
        slug: 'azzahra-yasmina-lisanti',
        name: 'Azzahra Yasmina Lisanti',
        role: MemberRole.ACARA_3,
        major: 'Ilmu Hukum',
        university: 'Universitas Kuningan',
        originAddress: 'Dukuh, Kadugede',
        imageUrl: '/assets/images/team/azzahra-yasmina-lisanti.jpg',
        description: 'Pelaksana divisi acara yang mengoordinasikan perizinan teknis kegiatan masyarakat.',
    },
    {
        id: 'tm-10',
        slug: 'yeni-alfiani',
        name: 'Yeni Alfiani',
        role: MemberRole.HUMAS_1,
        major: 'Kesehatan Masyarakat',
        university: 'UBHI',
        originAddress: 'Desa Kramatmulya, Kec. Kramatmulya',
        imageUrl: '/assets/images/team/yeni-aalfiani.jpg',
        description: 'Humas utama yang menjembatani komunikasi antara tim mahasiswa dengan perangkat desa.',
    },
    {
        id: 'tm-11',
        slug: 'tera-nurhalizah',
        name: 'Tera Nurhalizah',
        role: MemberRole.HUMAS_2,
        major: 'Pendidikan Matematika',
        university: 'Universitas Muhammadiyah Kuningan',
        originAddress: 'Desa Cileuleuy, Kec. Cigugur',
        imageUrl: '/assets/images/team/tera-nurhalizah.png',
        description: 'Staff humas koordinasi eksternal untuk kemitraan program pengabdian masyarakat.',
    },
    {
        id: 'tm-12',
        slug: 'yunita-hernawati',
        name: 'Yunita Hernawati',
        role: MemberRole.PDD_1,
        major: 'Manajemen Informasi Kesehatan',
        university: 'Poltekkes KMC Kuningan',
        originAddress: 'Desa Cihideunggirang, Kec. Cidahu',
        imageUrl: '/assets/images/team/yunita-hernawati.jpeg',
        description: 'Penanggung jawab visual grafis media cetak dan dokumentasi utama program KKN.',
    },
    {
        id: 'tm-13',
        slug: 'ani Inayah',
        name: 'Ani Inayah',
        role: MemberRole.PDD_2,
        major: 'PGSD',
        university: 'Universitas Kuningan',
        originAddress: 'Desa Kancana, Kec. Cikijing, Kab. Majalengka',
        imageUrl: '/assets/images/team/ani-inayah.jpeg',
        description: 'Staff PDD pelaksana dokumentasi visual video dan arsip digital kegiatan.',
    },
    {
        id: 'tm-14',
        slug: 'wahid-aropi',
        name: 'Wahid Aropi',
        role: MemberRole.PDD_3,
        major: 'Teknik Informatika',
        university: 'Universitas Kuningan',
        originAddress: '-',
        imageUrl: '/assets/images/team/wahid-aropi.jpeg',
        description: 'Staff PDD publikasi yang mengelola sistem media informasi digital web KKN.',
    },
    {
        id: 'tm-15',
        slug: 'salma-nurul-fathurrohmah',
        name: 'Salma Nurul Fathurrohmah',
        role: MemberRole.KONSUMSI_1,
        major: 'BKPI',
        university: 'STAIKU',
        originAddress: 'Desa Cieurih, Kec. Kecamatan Cidahu',
        imageUrl: '/assets/images/team/salma-nurul-fathurrohmah.jpg',
        description: 'Koordinator logistik pangan tim dan penyedia konsumsi agenda formal desa.',
    },
    {
        id: 'tm-16',
        slug: 'intan-rahmawati',
        name: 'Intan Rahmawati',
        role: MemberRole.KONSUMSI_2,
        major: 'Ekonomi Syariah',
        university: 'STAIKU',
        originAddress: 'Perumahan Griya Cendana Kuningan (Pagundan)',
        imageUrl: '/assets/images/team/intan-rahmawati.jpg',
        description: 'Staff bagian pemenuhan logistik konsumsi harian posko KKN dan acara.',
    },
    {
        id: 'tm-17',
        slug: 'nida-qonitah',
        name: 'Nida Qonitah',
        role: MemberRole.KONSUMSI_3,
        major: 'Pendidikan Matematika',
        university: 'Universitas Muhammadiyah Kuningan',
        originAddress: 'Desa Haurkuning, Kec. Nusaherang',
        imageUrl: '/assets/images/team/nida-qonitah.jpg',
        description: 'Staff konsumsi pendukung operasional ketersediaan kebutuhan logistik gizi.',
    },
    {
        id: 'tm-18',
        slug: 'lindan-maulana',
        name: 'Lindan Maulana',
        role: MemberRole.PERALATAN_1,
        major: 'Teknik Informatika',
        university: 'Universitas Kuningan',
        originAddress: 'Ds. Muncangela, Kec. Cipicung, Kab. Kuningan',
        imageUrl: '/assets/images/team/lindan-maulana.jpg',
        description: 'Penanggung jawab teknis perlengkapan, tata suara, pengadaan fasilitas, dan mobilitas fisik posko.',
    },
    {
        id: 'tm-19',
        slug: 'rizal-pahridzal',
        name: 'Rizal Pahridzal',
        role: MemberRole.PERALATAN_2,
        major: 'PJKR',
        university: 'Universitas Muhammadiyah Kuningan',
        originAddress: 'Desa Ciomas, Kec. Ciawigebang',
        imageUrl: '/assets/images/team/rizal-pahridzal.jpg',
        description: 'Staff logistik lapangan yang mengurus transportasi barang dan persiapan ruang acara.',
    },
];